language: python

os: linux
python: 3.5
dist: bionic

env:
    global:
        - CXX=g++-4.8
        # do not load /etc/boto.cfg with Python 3 incompatible plugin
        # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
        - BOTO_CONFIG=/doesnotexist
        - SYNDICATION_VALIDATE_AUTH=0
        - MAIL_SERVER='localhost'
        - MAIL_PORT=2225
        - MAIL_USERNAME=
        - MAIL_PASSWORD=
        - MAIL_USE_TLS=0
        - MAIL_USE_SSL=0
        - MAIL_DEBUG=1
        - MAIL_SUPPRESS_SEND=True
        # Using travis encrypted keys didn't solve the issue with cross-forks Pull Requests
        # So, we can use the test key taken from http://embed.ly/code site
        - EMBEDLY_KEY=fd92ebbc52fc43fb98f69e50e7893c13

services:
    - redis
    - docker
    - xvfb

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - docker pull barnybug/elasticsearch:1.7.2
    - docker run -d -p 127.0.0.1:9200:9200 barnybug/elasticsearch:1.7.2
    - docker pull mongo:3.4.23
    - docker run -d -p 127.0.0.1:27017:27017 mongo:3.4.23
    - docker ps -a
    - nvm install 8.12.0
    - nvm use 8.12.0
    - node --version
    - npm config set loglevel warn
    - npm install -g grunt-cli
    - pip install requests
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - export CHROME_BIN=`which google-chrome`
    - $CHROME_BIN --version

install:
    - cd $TRAVIS_BUILD_DIR/server
    - pip install --upgrade setuptools
    - pip install -r dev-requirements.txt
    - cd $TRAVIS_BUILD_DIR/client && npm install && cd .. ;

before_script:
    - cd $TRAVIS_BUILD_DIR/server
    - (nohup env LOG_CONFIG_FILE=../logging_travis_config.yml SUPERDESK_URL='http://localhost:5000/api' SUPERDESK_CLIENT_URL='http://localhost:9000' WEB_CONCURRENCY=3 WEB_TIMEOUT=8 SUPERDESK_TESTING='True' honcho start &)
    - cd $TRAVIS_BUILD_DIR/client
    - MARKETPLACE=true SYNDICATION=true grunt build --server='http://localhost:5000/api' --ws='ws://localhost:5100'
    - cd dist
    - while [ ! -f index.html ]; do sleep .5; done
    - (nohup sudo python3 -m smtpd -n -c DebuggingServer localhost:2225 &)
    - (nohup python3 -m http.server 9000 &)

script:
    - cd $TRAVIS_BUILD_DIR/server && nosetests --all-modules --nocapture;
    - cd $TRAVIS_BUILD_DIR/server && behave --format progress2 --logging-level ERROR ;
    - cd $TRAVIS_BUILD_DIR/server && flake8 ;
    - cd $TRAVIS_BUILD_DIR/client && npm run lint ;
    - cd $TRAVIS_BUILD_DIR/server
    - python3 app_init_elastic.py ;
    - python3 manage.py app:initialize_data ;
    - python3 manage.py users:create -u admin -p admin -e 'admin@example.com' --admin ;
    - python3 manage.py register_local_themes ;
    - python3 manage.py register_bloglist ;
    - cd $TRAVIS_BUILD_DIR/client
    - npm run webdriver-update
    - npm run e2e

after_script:
    - killall -9 python

after_success:
    - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
    - chmod +x trigger.sh
    - ./trigger.sh liveblog generator-liveblog-theme master $TRAVIS_ACCESS_TOKEN
